api_rest:
    resource: "@ApiRestBundle/Resources/config/routing.yml"
    prefix:   /api

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
