back_homepage:
    path:     /back/
    defaults: { _controller: BackBundle:Default:index }
back_cle:
    resource: "@BackBundle/Resources/config/routing/cle.yml"
    prefix:   /back/cle
back_user:
    resource: "@BackBundle/Resources/config/routing/user.yml"
    prefix:   /back/user
back_etat:
    resource: "@BackBundle/Resources/config/routing/etat.yml"
    prefix:   /back/etat
back_site:
    resource: "@BackBundle/Resources/config/routing/site.yml"
    prefix:   /back/site
back_affecte:
    resource: "@BackBundle/Resources/config/routing/affecte.yml"
    prefix:   /back/affecte
back_typeuser:
    resource: "@BackBundle/Resources/config/routing/typeuser.yml"
    prefix:   /back/typeuser
