api_rest_homepage:
    path:     /
    defaults: { _controller: ApiRestBundle:Default:index }
api_rest_listecle:
    path:     /listecle
    defaults: { _controller: ApiRestBundle:Default:listecle }
api_rest_detailcle:
    path:     /detailcle/{id}
    defaults: { _controller: ApiRestBundle:Default:detailcle }
    requirements:
      id: '\d+'
api_rest_listeuser:
    path:     /listeuser
    defaults: { _controller: ApiRestBundle:Default:listeuser }
api_rest_detailuser:
    path:     /detailuser/{id}
    defaults: { _controller: ApiRestBundle:Default:detailuser }
    requirements:
      id: '\d+'
