affecte_index:
    path:     /
    defaults: { _controller: "BackBundle:Affecte:showall" }
    methods:  GET

affecte_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:Affecte:show" }
    methods:  GET

affecte_new:
    path:     /new
    defaults: { _controller: "BackBundle:Affecte:new" }
    methods:  [GET, POST]

affecte_newForAffecte:
    path:     /new/{id}
    defaults: { _controller: "BackBundle:Affecte:new" }
    methods:  [GET, POST]
    requirements:
      id: '\d+'

affecte_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Affecte:edit" }
    methods:  [GET, POST]

affecte_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Affecte:delete" }
    methods:  DELETE
