etat_index:
    path:     /
    defaults: { _controller: "BackBundle:Etat:showall" }
    methods:  GET

etat_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:Etat:show" }
    methods:  GET

etat_new:
    path:     /new
    defaults: { _controller: "BackBundle:Etat:new" }
    methods:  [GET, POST]

etat_newForEtat:
    path:     /new/{id}
    defaults: { _controller: "BackBundle:Etat:new" }
    methods:  [GET, POST]
    requirements:
      id: '\d+'

etat_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:Etat:edit" }
    methods:  [GET, POST]

etat_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:Etat:delete" }
    methods:  DELETE
