user_index:
    path:     /
    defaults: { _controller: "BackBundle:User:showall" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "BackBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "BackBundle:User:new" }
    methods:  [GET, POST]

user_newForUser:
    path:     /new/{id}
    defaults: { _controller: "BackBundle:User:new" }
    methods:  [GET, POST]
    requirements:
      id: '\d+'

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackBundle:User:delete" }
    methods:  DELETE
