<?php

namespace BackBundle\Repository;

use BackBundle\Entity\User;
use Symfony\Component\HttpFoundation\JsonResponse;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository {

  public function listeuser() {
    $em = $this->getEntityManager()
        ->createQuery('SELECT i FROM BackBundle:User i ORDER BY i.nom ASC');
      return $em->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
  }
/*
  public function findAllSearchedByName($name) {
    return $this->getEntityManager()
        ->createQuery("SELECT i FROM BackOfficeBundle:Internaute i WHERE i.nom LIKE :name OR i.prenom LIKE :name ORDER BY i.nom, i.prenom ASC")->setParameter("name", '%'.$name.'%')->getResult();
  }

  public function findByInternauteOrderedRest() {
    $em= $this->getEntityManager()
    ->createQuery(
      'SELECT i FROM BackOfficeBundle:Internaute i ORDER BY i.nom ASC '
    );

    return $em->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
  }
  public function findByInternauteJson($id) {
    $em = $this->getEntityManager()->createQuery("SELECT i FROM BackOfficeBundle:Internaute i WHERE i.id = :id")->setParameter("id", $id);

    return $em->getOneOrNullResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
  }*/
}
